name: flutter_plugin
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 设备信息
  device_info_plus: ^9.0.2
  # 应用信息
  package_info_plus: ^8.0.0

  retrofit: '>=4.0.0 <5.0.0'
  # 状态管理
  flutter_riverpod: 2.4.0
  # 状态管理注解
  riverpod_annotation: ^2.1.1
  # 状态管理注解
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  # 国际化
  easy_localization: ^3.0.1
  # 图片缓存
  cached_network_image: ^3.2.3
  # 路由
  go_router: ^7.1.1
  dartz: ^0.10.1
  # 日志
  logger: ^1.3.0
  group_list_view: ^1.1.1
  recaptcha_enterprise_flutter: 18.4.2
  crypto: ^3.0.3
  path_provider: ^2.1.0
  path_provider_foundation: ^2.3.0
  url_launcher: ^6.1.12
  flutter_app_badger: ^1.5.0
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  #  三方登录依赖
  flutter_facebook_auth:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-plugin/flutter_facebook_auth.git
      ref: '7.1.2'
  google_sign_in: ^6.2.2
  lottie: ^3.1.2
  archive: ^4.0.0
  flutter_archive: 6.0.3
  # 图片选择
  image_picker: ^1.0.4
  video_thumbnail: ^0.5.3
  flutter_cached_pdfview: ^0.4.2
  flutter_cache_manager: ^3.3.1
  app_tracking_transparency: ^2.0.6
  mime: ^1.0.5
  # 图片裁剪
  image_cropper: ^7.0.0
  #侧滑
  flutter_slidable: ^3.0.0
  app_settings: ^5.0.0
  easy_refresh: ^3.3.4
  flutter_inappwebview: ^6.0.0
  flutter_smart_dialog: 4.9.4
  sqflite: ^2.3.0
  event_bus: ^2.0.0
  pinput: ^3.0.1
  flutter_js: ^0.8.0
  convert: ^3.1.1
  flutter_secure_storage: ^9.0.0
  # 检查google play是否可用
  google_api_availability: ^5.0.0
  # 经纬度转地区
  geocoding: ^3.0.0

  flutter_ali_auth:
    git:
      url: https://git.dreame.tech/terminal-library/dreame-android-app-flutter/dreame-android-sdk-onekeylogin-flutter.git
      ref: '1.4.1.2_mova'
  inapprating:
    git:
      url: https://git.dreame.tech/lijiajia/flutter_inapprating.git
      ref: '0.0.2'
  auto_size_text: ^3.0.0
  dots_indicator: ^2.1.1
  # Wi-Fi 扫描连接
  wifi_iot:
    git:
      url: https://git.dreame.tech/app-dev/WiFiFlutter.git
      ref: 'master'
      path: 'packages/wifi_iot'
      version: '0.3.19+1-c'
  wifi_scan: ^0.4.1
  network_info_plus: ^6.0.0
  connectivity_plus: ^6.0.5

  # 蓝牙操作
  flutter_blue_plus: 1.32.11
  lifecycle: ^0.8.0
  flutter_keyboard_size: ^1.0.1

  mobile_scanner:
    git:
      url: https://git.dreame.tech/app-dev/mobile_scanner_flutter.git
      ref: '4.1.2'

  flutter_curve25519: ^0.1.2
  encrypt: ^5.0.1
  flutter_timezone: ^1.0.8
  open_settings_plus: ^0.4.0
  qr_flutter: ^4.1.0
  flick_video_player: ^0.9.0
  wechat_assets_picker: ^9.2.0
  wechat_camera_picker:
    git:
      url: https://git.dreame.tech/flutter-dev/wechat_camera_picker.git
      ref: '0.0.3'
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^17.2.2
  flutter_icmp_ping: ^3.1.3
  location:
    git:
      url: https://git.dreame.tech/app-dev/flutterlocation.git
      ref: '6.0.0.4'
  pay_kit:
    git:
      url: https://git.dreame.tech/flutter-dev/pay_kit.git
      ref: '0.0.3'
  # flutter_network_connection: ^1.0.2
  # # flutter_icmp_ping: ^3.1.3
  # network_tools: ^5.0.2
  # dart_ping: ^9.0.1
  dreame_flutter_base_event_tracker:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-base/dreame-flutter-event-tracker.git
      ref: '0.0.5'
  dreame_flutter_plugin_tx_video:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-plugin/dreame-flutter-plugin-tx-video.git
      ref: '0.2.7_mova'
  dreame_flutter_plugin_open_setting:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-plugin/dreame-flutter-plugin-open-setting.git
      ref: '0.0.2'
  media_viewer:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-widget/dreame-flutter-widget-media_viewer.git
      ref: '0.0.2'

  dreame_flutter_base_mqtt:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-base/dreame-flutter-base-mqtt.git
      ref: '0.3.8'

  dreame_flutter_widget_dialog:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-widget/dreame-flutter-widget-dialog.git
      ref: '0.0.5'
  easy_debounce: ^2.0.3
  card_swiper: ^3.0.0
  carousel_slider: ^5.1.0
  video_player: ^2.10.0
  video_player_android: ^2.6.0
  scrollable_positioned_list: ^0.3.8
  visibility_detector: ^0.4.0+2
  openinstall_flutter_plugin: ^2.5.2
  pag:
    git:
      url: https://git.dreame.tech/flutter-dev/pag-flutter.git
      ref: 'v1.0.9+4'


dependency_overrides:
  http: ^0.13.1
  video_player_android: 2.6.0
  dreame_flutter_base_network:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-base/dreame-flutter-base-network.git
      ref: '0.2.1.2'
  dreame_flutter_base_model:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-base/dreame-flutter-base-model.git
      ref: '0.1.35_mova'
  flutter_inappwebview_ios:
    git:
      url: https://git.dreame.tech/flutter-dev/dreame-flutter-widget/flutter_inappwebview_ios.git
      ref: '1.0.14'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  build_runner:
  riverpod_generator: ^2.1.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  custom_lint_core: ^0.4.0
  # riverpod_lint: ^2.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    # 图片资源
    - assets/light/icons/3.0x/
    - assets/light/icons/2.0x/
    - assets/dark/icons/3.0x/
    # - assets/dark/

    # translations
    - assets/translations/
    # cert
    - assets/cert/cacert.pem
    - assets/cert/client.key
    - assets/cert/client.pem
    - assets/theme/default_style.json
    - assets/resource/
    - assets/home_device/
    # video
    #    - assets/video/
    #webview_resource
    - assets/webview_resource/mall/mall.zip
    # - assets/webview_resource/mall/
    # - assets/webview_resource/mall/index.html
    # - assets/theme/demo.html
    # - assets/webview_resource/mall/static/
    # - assets/webview_resource/mall/static/address/
    # - assets/webview_resource/mall/static/coupon/
    # - assets/webview_resource/mall/static/goodDetail/
    # - assets/webview_resource/mall/static/header/
    # - assets/webview_resource/mall/static/img/
    # - assets/webview_resource/mall/static/js/
    # - assets/webview_resource/mall/static/point/
    # - assets/webview_resource/mall/static/presale/
    # - assets/webview_resource/mall/static/tabbar/
    # - assets/webview_resource/mall/static/vipCenter/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.flutter_plugin
    iosBundleIdentifier: com.example.flutterPlugin
# flutter_intl:
#   enabled: true

wechat_kit:
  app_id: wx59efb945de8565a0
  universal_link: https://app.mova-tech.com/
alipay_kit:
  scheme: alipay0520
